image: continuumio/miniconda3:latest

install:
  stage: test
  script:
    - echo $CI_COMMIT_TAG
    - echo $CI_COMMIT_BRANCH
    - echo $CI_DEFAULT_BRANCH
    - conda create -n idtrackerai_test python=3.11 pytorch torchvision -c pytorch
    - source activate idtrackerai_test
    - apt-get update
    - apt-get install -y g++ ffmpeg libsm6 libxext6
    - python -m pip install .
    - python -m pip install pytest
    - pytest tests/unit_test.py --junitxml=report.xml

checks:
  stage: test
  script:
    - python -m pip install -U black[jupyter] flake8 isort
    - black . --check
    - isort . --check
    - flake8

release:
  stage: deploy
  rules: # if a tag has been generated
    - if: $CI_COMMIT_TAG
  script:
    - pip install -U twine build
    - pyasdasdthon -m build .
    - python -m twine upload dist/*
  release:
    tag_name: $CI_COMMIT_TAG
    description: "Automated GitLab release from $CI_COMMIT_TAG"
