image: continuumio/miniconda3:latest

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
#variables:
#  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

# Pip's cache doesn't store the python packages
# https://pip.pypa.io/en/stable/topics/caching/
#
# If you want to also cache the installed packages, you have to install
# them in a virtualenv and cache it as well.
#cache:
#  paths:
#    - .cache/pip
#    - venv/

before_script:
  - python --version  # For debugging
  - conda env create -f test-environment.yml
  - conda activate idtrackerai_test



install:
  stage: build
  script:
    - pip install .
    
pylint:
  stage: test
  before_script:
    - pip install pylint pylint-exit anybadge
  script:
    - mkdir ./pylint
    - pylint --output-format=text src/ tests/ --rcfile=pyproject.toml| tee ./pylint/pylint.log || pylint-exit $?
    - PYLINT_SCORE=$(sed -n 's/^Your code has been rated at \([-0-9.]*\)\/.*/\1/p' ./pylint/pylint.log)
    - anybadge --label=Pylint --file=pylint/pylint.svg --value=$PYLINT_SCORE 2=red 4=orange 8=yellow 10=green
    - echo "Pylint score is $PYLINT_SCORE"
  artifacts:
    paths:
      - ./pylint/

pytest:
  stage: test
  before_script:
    - pip install pytest
  script:
    - pytest tests/unit_tests.py --junitxml=report.xml
  artifacts:
    when: always
    reports:
      junit: report.xml

black:
  stage: test
  before_script:
    - pip install black
  script:
    - black . --check

flake8:
  stage: test
  before_script:
    - pip install flake8
  script:
    - flake8 . --select=E5,E7,E9,W6,F63,F7,F82 --max-line-length=120 --show-source --statistics
