image: continuumio/miniconda3:latest

test:
  script:
    - conda env create -f test-environment.yml
    - source activate idtrackerai_test
    - apt-get install -y g++ ffmpeg libsm6 libxext6
    - pip install .
    - pip install black flake8 pytest pylint pylint-exit anybadge
    - mkdir ./pylint
    - pylint --output-format=text src/ tests/ --rcfile=pyproject.toml| tee ./pylint/pylint.log || pylint-exit $?
    - PYLINT_SCORE=$(sed -n 's/^Your code has been rated at \([-0-9.]*\)\/.*/\1/p' ./pylint/pylint.log)
    - anybadge --label=Pylint --file=pylint/pylint.svg --value=$PYLINT_SCORE 2=red 4=orange 8=yellow 10=green
    - echo "Pylint score is $PYLINT_SCORE"
    - pytest tests/unit_tests.py --junitxml=report.xml
    - black . --check
    - flake8 . --select=E5,E7,E9,W6,F63,F7,F82 --max-line-length=120 --show-source --statistics
  artifacts:
    paths:
      - ./pylint/
    when: always
    reports:
      junit: report.xml
