[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"


[project]
name = "idtrackerai"
version = "4.0.9"
authors = [
    { name = "Francisco Romero Ferrero" },
    { name = "Mattia G. Bergomi" },
    { name = "Francisco J.H. Heras" },
    { name = "Ricardo Ribeiro" },
    { name = "Jordi Torrents" },
]
description = "A multi-animal tracking algorithm based on convolutional neural networks"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Development Status :: 3 - Alpha",
    "Environment :: Console",
    "Intended Audience :: Science/Research",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.7",
    "Topic :: Scientific/Engineering",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
]
dependencies = [
    "numpy >= 1.14.5",
    "natsort >= 5.0.2",
    "matplotlib >= 3.5.3",
    "seaborn >= 0.8",
    "rich",
    "joblib >= 0.11",
    "scikit-learn >= 1.0.1",
    "pyyaml >= 3.12",
    "psutil >= 5.4.3",
    "h5py >= 2.7.0",
    "xlib >= 0.21",
    "msgpack-numpy >= 0.3.9",
    "msgpack-python >= 0.4.8",
    "scipy > 1.8.0",
    "scikit-learn >= 0.0",
    "tables >= 3.3.0",
    "dask >= 0.17.0",
    "opencv-python ",
    "confapp >= 1.1.11",
    "pyqt6",
    'shapely',
    'superqt',
]

[project.urls]
"Homepage" = "https://idtrackerai.readthedocs.io/en/latest/"
"Repository" = "https://gitlab.com/polavieja_lab/idtrackerai"

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
"idtrackerai.data" = ["**"]

[project.scripts]
idtrackerai_test = "idtrackerai_app.__main__:general_test"
idtrackerai = "idtrackerai_app.__main__:main"

[tool.pytest.ini_options]
log_file_format = "[%(asctime)s %(levelname)8s] %(message)s (%(filename)s:%(lineno)s)"
log_file = 'pytest.log'
testpaths = ["tests"]
log_file_level = 0
addopts = '-v'
