"""
Core SAM 3 wrapper for text-prompted animal segmentation using ultralytics.

This module provides ``SAM3AnimalSegmenter`` which uses the **ultralytics**
SAM 3 integration (``sam3.pt``) for unified text-prompted segmentation and
tracking.  SAM 3 combines detection, segmentation, and tracking in a single
model — no separate GroundingDINO step is needed.

**VRAM Management**: The ultralytics predictor is loaded lazily on the first
call to :meth:`segment_video` and released explicitly via :meth:`release`.
"""

import gc
import logging
import os
from pathlib import Path
from typing import Any

import numpy as np

logger = logging.getLogger("idtrackerai.sam3.predictor")


def _free_gpu():
    """Aggressively free GPU memory."""
    import torch

    gc.collect()
    if torch.cuda.is_available():
        try:
            torch.cuda.empty_cache()
            torch.cuda.synchronize()
        except RuntimeError as exc:
            logger.warning(f"CUDA cleanup warning (non-fatal): {exc}")


def _find_sam3_weights() -> str:
    """Locate the ``sam3.pt`` weight file.

    Search order:
        1. ``weights/`` directory relative to the package root
        2. Current working directory
        3. Default name ``sam3.pt`` (ultralytics may auto-download)

    Returns
    -------
    str
        Absolute path to the weight file, or ``"sam3.pt"`` as fallback.
    """
    # 1. Package-relative weights/ directory
    weights_dir = Path(__file__).resolve().parents[4] / "weights"
    candidate = weights_dir / "sam3.pt"
    if candidate.is_file():
        return str(candidate)

    # 2. Current working directory
    cwd_candidate = Path.cwd() / "sam3.pt"
    if cwd_candidate.is_file():
        return str(cwd_candidate)

    # 3. Fallback — let ultralytics handle resolution
    logger.info(
        "sam3.pt not found locally; ultralytics will attempt to resolve it"
    )
    return "sam3.pt"


class SAM3AnimalSegmenter:
    """Text-prompted video segmenter using ultralytics SAM 3.

    SAM 3 performs **Promptable Concept Segmentation** — it detects,
    segments, and tracks objects from a natural-language text prompt
    in a single unified model.  No separate object detector is needed.

    Parameters
    ----------
    checkpoint : str or Path, optional
        Path to the ``sam3.pt`` weight file.  If empty or not found,
        :func:`_find_sam3_weights` auto-discovers it.
    device : str
        Device for inference: ``"cuda"`` or ``"cpu"``.
    """

    def __init__(
        self,
        checkpoint: str | Path = "",
        device: str = "cuda",
    ):
        if checkpoint and Path(checkpoint).is_file():
            self.checkpoint = str(checkpoint)
        else:
            self.checkpoint = _find_sam3_weights()

        self.device = device
        self._predictor = None

    # ------------------------------------------------------------------
    # Video-level segmentation
    # ------------------------------------------------------------------
    def segment_video(
        self,
        frames_dir: str,
        text_prompt: str,
        number_of_animals: int,
        confidence_threshold: float = 0.25,
        additional_prompts: dict[int, dict] | None = None,
        video_path: str | None = None,
    ) -> dict[int, dict[int, np.ndarray]]:
        """Run text-prompted video segmentation with ultralytics SAM 3.

        The method tries ``SAM3VideoSemanticPredictor`` first (full
        spatio-temporal tracking).  If the video predictor is not
        available in the installed ultralytics version, it falls back
        to per-frame ``SAM3SemanticPredictor``.

        Parameters
        ----------
        frames_dir : str
            Directory containing numbered JPEG frames.
        text_prompt : str
            Text description of the animal (e.g. ``"fish"``).
        number_of_animals : int
            Expected number of animals — used for validation only.
        confidence_threshold : float
            Detection confidence threshold.
        additional_prompts : dict, optional
            Dict mapping ``obj_id -> {"frame_idx": int, "points":
            np.array, "labels": np.array}`` for point-prompt based
            refinement of missed animals. Generated by
            ``generate_hybrid_prompts()`` in ``prompting.py``.

        Returns
        -------
        video_segments : dict
            ``{frame_idx: {obj_id: binary_mask_array}}``
        """
        if not text_prompt:
            raise ValueError(
                "text_prompt is required for SAM 3 segmentation. "
                "Set sam3_text_prompt in your parameter file."
            )

        # Get sorted frame paths
        frame_names = sorted(
            [
                p
                for p in os.listdir(frames_dir)
                if os.path.splitext(p)[-1].lower() in (".jpg", ".jpeg")
            ],
            key=lambda p: int(os.path.splitext(p)[0]),
        )

        if not frame_names:
            raise FileNotFoundError(f"No JPEG frames found in {frames_dir}")

        logger.info(f"Found {len(frame_names)} frames in {frames_dir}")
        logger.info(f"Using SAM 3 checkpoint: {self.checkpoint}")
        logger.info(f"Text prompt: '{text_prompt}'")

        # Try video-level predictor first (needs actual video file), fall back to per-frame
        strategy_used = "video"
        try:
            if video_path is None:
                raise ValueError("No video_path provided, skipping video predictor")
            video_segments = self._segment_video_predictor(
                video_path, frame_names, text_prompt, confidence_threshold
            )
        except (ImportError, AttributeError, TypeError, ValueError) as exc:
            logger.warning(
                f"SAM3VideoSemanticPredictor unavailable ({exc}), "
                f"falling back to per-frame segmentation"
            )
            video_segments = self._segment_per_frame(
                frames_dir, frame_names, text_prompt, confidence_threshold
            )
            strategy_used = "per-frame"

        # Fix 6: Diagnostic logging — report tracking ID availability
        sample_frame = video_segments.get(0, {})
        sample_ids = list(sample_frame.keys()) if sample_frame else []
        has_any_track_ids = any(
            any(vid for vid in video_segments.get(f, {}).keys())
            for f in range(min(5, len(frame_names)))
        )
        logger.info(
            f"Segmentation strategy: {strategy_used} | "
            f"First frame IDs: {sample_ids} | "
            f"Tracking IDs present: {has_any_track_ids}"
        )

        # Fill missing frames with empty dicts
        for frame_idx in range(len(frame_names)):
            if frame_idx not in video_segments:
                video_segments[frame_idx] = {}

        # Validate
        self._validate_detections(
            video_segments, number_of_animals, len(frame_names)
        )

        total_masks = sum(len(v) for v in video_segments.values())
        logger.info(
            f"Segmentation complete: {len(video_segments)} frames, "
            f"{total_masks} total object-masks"
        )

        return video_segments

    # ------------------------------------------------------------------
    # Strategy 1: SAM3VideoSemanticPredictor (full video tracking)
    # ------------------------------------------------------------------
    def _segment_video_predictor(
        self,
        video_path: str,
        frame_names: list[str],
        text_prompt: str,
        confidence_threshold: float,
    ) -> dict[int, dict[int, np.ndarray]]:
        """Segment using the video-level semantic predictor (tracking)."""
        from ultralytics.models.sam import SAM3VideoSemanticPredictor

        logger.info("Using SAM3VideoSemanticPredictor (video tracking mode)")

        overrides = dict(
            conf=confidence_threshold,
            task="segment",
            mode="predict",
            model=self.checkpoint,
            device=self.device,
        )

        predictor = SAM3VideoSemanticPredictor(overrides=overrides)

        # Run inference on the actual video file (not the frames directory)
        results = predictor(source=video_path, text=text_prompt, stream=True)

        video_segments: dict[int, dict[int, np.ndarray]] = {}

        for frame_idx, result in enumerate(results):
            frame_masks: dict[int, np.ndarray] = {}

            if result.masks is not None and len(result.masks) > 0:
                masks_data = result.masks.data.cpu().numpy()

                # Use tracking IDs from the video predictor if available,
                # otherwise fall back to positional indices
                has_track_ids = (
                    result.boxes is not None
                    and hasattr(result.boxes, "id")
                    and result.boxes.id is not None
                )

                if has_track_ids:
                    track_ids = result.boxes.id.cpu().numpy().astype(int)
                    for idx, track_id in enumerate(track_ids):
                        if idx < masks_data.shape[0]:
                            binary_mask = (masks_data[idx] > 0.5).astype(np.uint8)
                            frame_masks[int(track_id)] = binary_mask
                    if frame_idx == 0:
                        logger.info(
                            f"Video predictor providing tracking IDs "
                            f"(first frame IDs: {list(frame_masks.keys())})"
                        )
                else:
                    for obj_idx in range(masks_data.shape[0]):
                        binary_mask = (masks_data[obj_idx] > 0.5).astype(np.uint8)
                        frame_masks[obj_idx + 1] = binary_mask

            video_segments[frame_idx] = frame_masks

        del predictor
        _free_gpu()
        logger.info("SAM3VideoSemanticPredictor released from GPU")

        return video_segments

    # ------------------------------------------------------------------
    # Strategy 2: SAM3SemanticPredictor (per-frame fallback)
    # ------------------------------------------------------------------
    def _segment_per_frame(
        self,
        frames_dir: str,
        frame_names: list[str],
        text_prompt: str,
        confidence_threshold: float,
    ) -> dict[int, dict[int, np.ndarray]]:
        """Fallback: segment each frame independently.

        Uses Hungarian matching on centroids between consecutive frames
        to maintain consistent object IDs even without video-level
        tracking.
        """
        from ultralytics.models.sam import SAM3SemanticPredictor

        logger.info("Using SAM3SemanticPredictor (per-frame mode with Hungarian matching)")

        overrides = dict(
            conf=confidence_threshold,
            task="segment",
            mode="predict",
            model=self.checkpoint,
            device=self.device,
        )

        predictor = SAM3SemanticPredictor(overrides=overrides)

        video_segments: dict[int, dict[int, np.ndarray]] = {}

        cuda_failed = False
        prev_centroids: dict[int, tuple[float, float]] = {}  # {obj_id: (cy, cx)}
        next_available_id = 1

        for frame_idx, fname in enumerate(frame_names):
            frame_path = os.path.join(frames_dir, fname)
            raw_masks: list[np.ndarray] = []

            if not cuda_failed:
                try:
                    results = predictor(source=frame_path, text=text_prompt)

                    if results and results[0].masks is not None:
                        masks_data = results[0].masks.data.cpu().numpy()

                        for obj_idx in range(masks_data.shape[0]):
                            binary_mask = (
                                (masks_data[obj_idx] > 0.5).astype(np.uint8)
                            )
                            raw_masks.append(binary_mask)

                except RuntimeError as exc:
                    if "CUDA" in str(exc) or "device-side assert" in str(exc):
                        logger.error(
                            f"Frame {frame_idx}: CUDA error ({exc}). "
                            f"Remaining frames will be empty. "
                            f"Try running with --device cpu or check GPU compatibility."
                        )
                        cuda_failed = True
                    else:
                        logger.warning(
                            f"Frame {frame_idx}: SAM 3 inference failed ({exc})"
                        )
                except Exception as exc:
                    logger.warning(
                        f"Frame {frame_idx}: SAM 3 inference failed ({exc})"
                    )

            # Hungarian matching: assign consistent IDs based on centroids
            frame_masks: dict[int, np.ndarray] = {}

            if raw_masks:
                # Compute centroids for current frame's masks
                curr_centroids: list[tuple[float, float]] = []
                for mask in raw_masks:
                    ys, xs = np.where(mask > 0)
                    if len(ys) > 0:
                        curr_centroids.append((float(ys.mean()), float(xs.mean())))
                    else:
                        curr_centroids.append((0.0, 0.0))

                if prev_centroids and curr_centroids:
                    # Build cost matrix: distance from each prev ID to each curr detection
                    prev_ids = list(prev_centroids.keys())
                    prev_pts = [prev_centroids[pid] for pid in prev_ids]

                    cost_matrix = np.zeros((len(prev_pts), len(curr_centroids)))
                    for i, (py, px) in enumerate(prev_pts):
                        for j, (cy, cx) in enumerate(curr_centroids):
                            cost_matrix[i, j] = np.sqrt((py - cy)**2 + (px - cx)**2)

                    try:
                        from scipy.optimize import linear_sum_assignment
                        row_ind, col_ind = linear_sum_assignment(cost_matrix)

                        assigned_cols: set[int] = set()
                        new_centroids: dict[int, tuple[float, float]] = {}

                        for r, c in zip(row_ind, col_ind):
                            obj_id = prev_ids[r]
                            frame_masks[obj_id] = raw_masks[c]
                            new_centroids[obj_id] = curr_centroids[c]
                            assigned_cols.add(c)

                        # Assign new IDs to unmatched detections
                        for c in range(len(raw_masks)):
                            if c not in assigned_cols:
                                frame_masks[next_available_id] = raw_masks[c]
                                new_centroids[next_available_id] = curr_centroids[c]
                                next_available_id += 1

                        prev_centroids = new_centroids

                    except ImportError:
                        # scipy not available — fall back to positional IDs
                        logger.warning(
                            "scipy not available for Hungarian matching, "
                            "using positional IDs"
                        )
                        prev_centroids = {}
                        for obj_idx, mask in enumerate(raw_masks):
                            obj_id = obj_idx + 1
                            frame_masks[obj_id] = mask
                            prev_centroids[obj_id] = curr_centroids[obj_idx]
                else:
                    # First frame or no previous centroids
                    prev_centroids = {}
                    for obj_idx, mask in enumerate(raw_masks):
                        obj_id = next_available_id
                        frame_masks[obj_id] = mask
                        prev_centroids[obj_id] = curr_centroids[obj_idx]
                        next_available_id += 1

            video_segments[frame_idx] = frame_masks

            if frame_idx % 100 == 0 and frame_idx > 0:
                logger.info(
                    f"Processed {frame_idx}/{len(frame_names)} frames"
                )

        del predictor
        _free_gpu()
        logger.info("SAM3SemanticPredictor released from GPU")

        return video_segments

    # ------------------------------------------------------------------
    # Validation & cleanup
    # ------------------------------------------------------------------
    def _validate_detections(
        self,
        video_segments: dict[int, dict[int, np.ndarray]],
        number_of_animals: int,
        num_frames: int,
    ) -> None:
        """Log warnings if detection count doesn't match expected."""
        if number_of_animals <= 0:
            return

        frames_too_few = sum(
            1
            for f in range(num_frames)
            if len(video_segments.get(f, {})) < number_of_animals
        )
        frames_too_many = sum(
            1
            for f in range(num_frames)
            if len(video_segments.get(f, {})) > number_of_animals
        )

        if frames_too_few:
            pct = frames_too_few / num_frames * 100
            logger.warning(
                f"Fewer objects than expected in {frames_too_few} frames "
                f"({pct:.1f}%). Expected {number_of_animals}."
            )
        if frames_too_many:
            pct = frames_too_many / num_frames * 100
            logger.warning(
                f"More objects than expected in {frames_too_many} frames "
                f"({pct:.1f}%). Expected {number_of_animals}."
            )

    # ------------------------------------------------------------------
    # Point-prompt segmentation (for hybrid prompting)
    # ------------------------------------------------------------------
    def segment_frame_with_points(
        self,
        frame_path: str,
        points: np.ndarray,
        labels: np.ndarray,
        confidence_threshold: float = 0.25,
    ) -> dict[int, np.ndarray]:
        """Segment a single frame using explicit point prompts.

        This is used by the hybrid prompting system: when SAM 3's text
        prompt misses some animals, the legacy threshold pipeline finds
        their centroids and feeds them here as foreground point prompts.

        Parameters
        ----------
        frame_path : str
            Path to the frame image (JPEG).
        points : np.ndarray
            Array of shape ``(N, 2)`` with ``(x, y)`` point coordinates.
        labels : np.ndarray
            Array of shape ``(N,)`` with point labels (1 = foreground).
        confidence_threshold : float
            Confidence threshold for mask acceptance.

        Returns
        -------
        masks : dict
            ``{obj_id: binary_mask_array}`` for each detected object.
        """
        from ultralytics.models.sam import SAM3SemanticPredictor

        overrides = dict(
            conf=confidence_threshold,
            task="segment",
            mode="predict",
            model=self.checkpoint,
            device=self.device,
        )

        predictor = SAM3SemanticPredictor(overrides=overrides)
        masks: dict[int, np.ndarray] = {}

        try:
            results = predictor(
                source=frame_path, points=points, labels=labels
            )

            if results and results[0].masks is not None:
                masks_data = results[0].masks.data.cpu().numpy()
                for obj_idx in range(masks_data.shape[0]):
                    binary_mask = (masks_data[obj_idx] > 0.5).astype(np.uint8)
                    masks[obj_idx + 1] = binary_mask

            logger.info(
                f"Point-prompt segmentation produced {len(masks)} masks "
                f"from {len(points)} point prompts"
            )
        except Exception as exc:
            logger.warning(
                f"Point-prompt segmentation failed ({exc}). "
                f"Missed animals will not be recovered for this frame."
            )
        finally:
            del predictor
            _free_gpu()

        return masks

    def release(self):
        """Free any remaining GPU memory."""
        self._predictor = None
        _free_gpu()
        logger.info("GPU memory cleanup complete")
