from PyQt6.QtGui import QColor, QPalette

ColorRole = QPalette.ColorRole
Disabled = QPalette.ColorGroup.Disabled

custom = QPalette()
background = "#202124"
mid_background = "#2C2D2F"
light_bkg = "#3F4042"
blue = "#8AB4F7"
blue = "#AAD4FF"
almost_white = "#FDFDFD"
placeholder_color = "#B0B0B0"
red = "#FF0000"
custom.setColor(ColorRole.Window, QColor(background))
custom.setColor(ColorRole.WindowText, QColor(almost_white))
custom.setColor(ColorRole.Base, QColor(light_bkg))
custom.setColor(ColorRole.AlternateBase, QColor(mid_background))
custom.setColor(ColorRole.Text, QColor(almost_white))
custom.setColor(ColorRole.Button, QColor(mid_background))
custom.setColor(ColorRole.ButtonText, QColor(blue))
custom.setColor(ColorRole.Highlight, QColor(blue))
custom.setColor(ColorRole.HighlightedText, QColor(background))
custom.setColor(ColorRole.PlaceholderText, QColor(placeholder_color))
custom.setColor(Disabled, ColorRole.WindowText, custom.windowText().color().darker())
custom.setColor(Disabled, ColorRole.Button, custom.button().color().darker())
custom.setColor(Disabled, ColorRole.ButtonText, custom.buttonText().color().darker())
custom.setColor(Disabled, ColorRole.Base, custom.base().color().darker())
custom.setColor(Disabled, ColorRole.Text, custom.text().color().darker())
custom.setColor(
    Disabled, ColorRole.PlaceholderText, custom.placeholderText().color().darker()
)
custom.setColor(ColorRole.BrightText, QColor(red))
custom.setColor(ColorRole.Light, QColor(red))
custom.setColor(ColorRole.Midlight, QColor(red))
custom.setColor(ColorRole.Dark, QColor(red))
custom.setColor(ColorRole.Shadow, QColor(red))
custom.setColor(ColorRole.Mid, QColor(red))
custom.setColor(ColorRole.Link, QColor(red))
custom.setColor(ColorRole.LinkVisited, QColor(red))
custom.setColor(ColorRole.ToolTipBase, QColor("#ffffdc"))
custom.setColor(ColorRole.ToolTipText, QColor("#000000"))
custom.setColor(ColorRole.NoRole, QColor(red))


dark = QPalette()
dark.setColor(ColorRole.WindowText, QColor("#f0f0f0"))
dark.setColor(ColorRole.Button, QColor("#323232"))
dark.setColor(ColorRole.Light, QColor("#4b4b4b"))
dark.setColor(ColorRole.Midlight, QColor("#2a2a2a"))
dark.setColor(ColorRole.Dark, QColor("#212121"))
dark.setColor(ColorRole.Mid, QColor("#262626"))
dark.setColor(ColorRole.Text, QColor("#f0f0f0"))
dark.setColor(ColorRole.BrightText, QColor("#4b4b4b"))
dark.setColor(ColorRole.ButtonText, QColor("#f0f0f0"))
dark.setColor(ColorRole.Base, QColor("#242424"))
dark.setColor(ColorRole.Window, QColor("#323232"))
dark.setColor(ColorRole.Shadow, QColor("#191919"))
dark.setColor(ColorRole.Highlight, QColor("#308cc6"))
dark.setColor(ColorRole.HighlightedText, QColor("#303030"))
dark.setColor(ColorRole.Link, QColor("#308cc6"))
dark.setColor(ColorRole.LinkVisited, QColor("#ff00ff"))
dark.setColor(ColorRole.AlternateBase, QColor("#2b2b2b"))
dark.setColor(ColorRole.ToolTipBase, QColor("#ffffdc"))
dark.setColor(ColorRole.ToolTipText, QColor("#000000"))
dark.setColor(ColorRole.PlaceholderText, QColor("#f0f0f0"))
dark.setColor(ColorRole.NoRole, QColor("#000000"))
dark.setColor(Disabled, ColorRole.WindowText, QColor("#828282"))
dark.setColor(Disabled, ColorRole.Button, QColor("#323232"))
dark.setColor(Disabled, ColorRole.Light, QColor("#4b4b4b"))
dark.setColor(Disabled, ColorRole.Midlight, QColor("#2a2a2a"))
dark.setColor(Disabled, ColorRole.Dark, QColor("#bebebe"))
dark.setColor(Disabled, ColorRole.Mid, QColor("#262626"))
dark.setColor(Disabled, ColorRole.Text, QColor("#828282"))
dark.setColor(Disabled, ColorRole.BrightText, QColor("#4b4b4b"))
dark.setColor(Disabled, ColorRole.ButtonText, QColor("#828282"))
dark.setColor(Disabled, ColorRole.Base, QColor("#323232"))
dark.setColor(Disabled, ColorRole.Window, QColor("#323232"))
dark.setColor(Disabled, ColorRole.Shadow, QColor("#252525"))
dark.setColor(Disabled, ColorRole.Highlight, QColor("#919191"))
dark.setColor(Disabled, ColorRole.HighlightedText, QColor("#f0f0f0"))
dark.setColor(Disabled, ColorRole.Link, QColor("#308cc6"))
dark.setColor(Disabled, ColorRole.LinkVisited, QColor("#ff00ff"))
dark.setColor(Disabled, ColorRole.AlternateBase, QColor("#2b2b2b"))
dark.setColor(Disabled, ColorRole.ToolTipBase, QColor("#ffffdc"))
dark.setColor(Disabled, ColorRole.ToolTipText, QColor("#000000"))
dark.setColor(Disabled, ColorRole.PlaceholderText, QColor("#f0f0f0"))
dark.setColor(Disabled, ColorRole.NoRole, QColor("#000000"))


light = QPalette()
light.setColor(ColorRole.WindowText, QColor("#000000"))
light.setColor(ColorRole.Button, QColor("#efefef"))
light.setColor(ColorRole.Light, QColor("#ffffff"))
light.setColor(ColorRole.Midlight, QColor("#cacaca"))
light.setColor(ColorRole.Dark, QColor("#9f9f9f"))
light.setColor(ColorRole.Mid, QColor("#b8b8b8"))
light.setColor(ColorRole.Text, QColor("#000000"))
light.setColor(ColorRole.BrightText, QColor("#ffffff"))
light.setColor(ColorRole.ButtonText, QColor("#000000"))
light.setColor(ColorRole.Base, QColor("#ffffff"))
light.setColor(ColorRole.Window, QColor("#efefef"))
light.setColor(ColorRole.Shadow, QColor("#767676"))
light.setColor(ColorRole.Highlight, QColor("#308cc6"))
light.setColor(ColorRole.HighlightedText, QColor("#ffffff"))
light.setColor(ColorRole.Link, QColor("#0000ff"))
light.setColor(ColorRole.LinkVisited, QColor("#ff00ff"))
light.setColor(ColorRole.AlternateBase, QColor("#d5d5d5"))
light.setColor(ColorRole.ToolTipBase, QColor("#ffffdc"))
light.setColor(ColorRole.ToolTipText, QColor("#000000"))
light.setColor(ColorRole.PlaceholderText, QColor("#a0a0a0"))
light.setColor(ColorRole.NoRole, QColor("#000000"))
light.setColor(Disabled, ColorRole.WindowText, QColor("#bebebe"))
light.setColor(Disabled, ColorRole.Button, QColor("#efefef"))
light.setColor(Disabled, ColorRole.Light, QColor("#ffffff"))
light.setColor(Disabled, ColorRole.Midlight, QColor("#cacaca"))
light.setColor(Disabled, ColorRole.Dark, QColor("#bebebe"))
light.setColor(Disabled, ColorRole.Mid, QColor("#b8b8b8"))
light.setColor(Disabled, ColorRole.Text, QColor("#bebebe"))
light.setColor(Disabled, ColorRole.BrightText, QColor("#ffffff"))
light.setColor(Disabled, ColorRole.ButtonText, QColor("#bebebe"))
light.setColor(Disabled, ColorRole.Base, QColor("#efefef"))
light.setColor(Disabled, ColorRole.Window, QColor("#efefef"))
light.setColor(Disabled, ColorRole.Shadow, QColor("#b1b1b1"))
light.setColor(Disabled, ColorRole.Highlight, QColor("#919191"))
light.setColor(Disabled, ColorRole.HighlightedText, QColor("#ffffff"))
light.setColor(Disabled, ColorRole.Link, QColor("#0000ff"))
light.setColor(Disabled, ColorRole.LinkVisited, QColor("#ff00ff"))
light.setColor(Disabled, ColorRole.AlternateBase, QColor("#f7f7f7"))
light.setColor(Disabled, ColorRole.ToolTipBase, QColor("#ffffdc"))
light.setColor(Disabled, ColorRole.ToolTipText, QColor("#000000"))
light.setColor(Disabled, ColorRole.PlaceholderText, light.placeholderText().color())
light.setColor(Disabled, ColorRole.NoRole, QColor("#000000"))
